Salon/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using Salon.Mappings;
using SalonServices.Dto;

namespace Salon.Controllers
{
    public class CountryController : Controller
    {
        private readonly IReferenceServices _referenceServices;
        public CountryController(IReferenceServices pReferenceServices)
        {
            this._referenceServices = pReferenceServices;
        }

        public async Task<IActionResult> SuccessfulCountries(int pPersonId)
        {
            var lDtos = await this._referenceServices.GetSuccessfulCountries(pPersonId);
            var lCountries = lDtos.Select(itm => Mapping.Mapper.Map<CountryViewModel>(itm)).ToList();
            int row = 1;
            foreach (var lCountry in lCountries)
            {
                lCountry.Number = row;
                row++;
            }

			var lModel = new CountryIndexViewModel()
			{
				Countries = lCountries,
			};
			return View(lModel);
        }

        public async Task<IActionResult> Index(string successMessage = null, string failureMessage = null)
        {
            var lDtos = await this._referenceServices.GetCountries();

            var lModel = new CountryIndexViewModel()
            {
                SuccessMessage = successMessage,
                FailureMessage = failureMessage,
                Countries = lDtos.Select(itm => Mapping.Mapper.Map<CountryViewModel>(itm)).ToList(),
            };
            return View(lModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new CreateCountryViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateCountryViewModel pCreateModel)
        {
            if(!this.ModelState.IsValid)
            {
                pCreateModel.Errors = this.ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return View(pCreateModel);
            }

            // map to Dto
            var lDtoToCreate = Mapping.Mapper.Map<CreateCountryDto>(pCreateModel);
            await this._referenceServices.CreateCountry(lDtoToCreate);

            return RedirectToAction("Index", new { successMessage = "Country successfully created" });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            CountryDto lCountryDto = await this._referenceServices.GetCountryById(id);
            var lViewModelToEdit = Mapping.Mapper.Map<CountryViewModel>(lCountryDto);
            //this._referenceServices.
            return View(lViewModelToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CountryViewModel pViewModelToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(pViewModelToUpdate);
            }

            // map to Dto
            CountryDto lCountryDto = Mapping.Mapper.Map<CountryDto>(pViewModelToUpdate);

            await this._referenceServices.UpdateCountry(lCountryDto);

            return RedirectToAction("Index", new { successMessage = "Country successfully updated" });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await this._referenceServices.DeleteCountry(id);
            return RedirectToAction("Index", new { successMessage = "Country successfully deleted" });
        }
    }
}

Salon/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using Salon.Mappings;
using SalonServices.Dto;
using Salon.Models.Submission;

namespace Salon.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonAwardService _personAwardService;
        public PersonController(IPersonAwardService _personAwardService)
        {
            this._personAwardService = _personAwardService;
        }

        public async Task<IActionResult> Index()
        {
            var lDtos = await this._personAwardService.GetAllPersons();

            var lModel = new PersonIndexViewModel()
            {
                People = lDtos.Select(itm => Mapping.Mapper.Map<BasicPersonViewModel>(itm)).ToList(),
            };
            return View(lModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var lAwardLevelDto = await this._personAwardService.GetAwardLevelsForPerson(id);
            return View(Mapping.Mapper.Map<PersonAwardTableViewModel>(lAwardLevelDto));
        }

        [HttpGet]
        public async Task<IActionResult> PsaList(int pPersonId, string pSectionCode)
        {
            var lPsaSubmissionDto = await this._personAwardService.GetOrganisationSubmissionList(pPersonId, "PSA", pSectionCode);
            return View(Mapping.Mapper.Map<PsaSubmissionViewModel>(lPsaSubmissionDto));
        }
    }
}

Salon/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Salon</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/knockout/knockout-3.4.2.js"></script>
    <script src="~/js/knockout/knockout.autocomplete.js"></script>
    <script src="~/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/knockout/knockout.datepicker.js"></script>
    <link rel="stylesheet" href="~/css/bootstrap-datepicker3.min.css" />

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/js/knockout/knockout.autocomplete.css" />

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Salon</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Person" asp-action="Index">People</a></li>
                    <li><a asp-area="" asp-controller="SectionType" asp-action="Index">Section Types</a></li>
                    <li><a asp-area="" asp-controller="Country" asp-action="Index">Countries</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Salon</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>