Salon/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using Salon.Mappings;
using SalonServices.Dto;

namespace Salon.Controllers
{
    public class CountryController : Controller
    {
        private readonly IReferenceServices _referenceServices;
        public CountryController(IReferenceServices pReferenceServices)
        {
            this._referenceServices = pReferenceServices;
        }

        public async Task<IActionResult> SuccessfulCountries(int pPersonId)
        {
            var lDtos = await this._referenceServices.GetSuccessfulCountries(pPersonId);
            var lCountries = lDtos.Select(itm => Mapping.Mapper.Map<CountryViewModel>(itm)).ToList();
            int row = 1;
            foreach (var lCountry in lCountries)
            {
                lCountry.Number = row;
                row++;
            }

			var lModel = new CountryIndexViewModel()
			{
				Countries = lCountries,
			};
			return View(lModel);
        }

        public async Task<IActionResult> Index(string successMessage = null, string failureMessage = null)
        {
            var lDtos = await this._referenceServices.GetCountries();

            var lModel = new CountryIndexViewModel()
            {
                SuccessMessage = successMessage,
                FailureMessage = failureMessage,
                Countries = lDtos.Select(itm => Mapping.Mapper.Map<CountryViewModel>(itm)).ToList(),
            };
            return View(lModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new CreateCountryViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateCountryViewModel pCreateModel)
        {
            if(!this.ModelState.IsValid)
            {
                pCreateModel.Errors = this.ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return View(pCreateModel);
            }

            // map to Dto
            var lDtoToCreate = Mapping.Mapper.Map<CreateCountryDto>(pCreateModel);
            await this._referenceServices.CreateCountry(lDtoToCreate);

            return RedirectToAction("Index", new { successMessage = "Country successfully created" });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            CountryDto lCountryDto = await this._referenceServices.GetCountryById(id);
            var lViewModelToEdit = Mapping.Mapper.Map<CountryViewModel>(lCountryDto);
            //this._referenceServices.
            return View(lViewModelToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CountryViewModel pViewModelToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(pViewModelToUpdate);
            }

            // map to Dto
            CountryDto lCountryDto = Mapping.Mapper.Map<CountryDto>(pViewModelToUpdate);

            await this._referenceServices.UpdateCountry(lCountryDto);

            return RedirectToAction("Index", new { successMessage = "Country successfully updated" });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await this._referenceServices.DeleteCountry(id);
            return RedirectToAction("Index", new { successMessage = "Country successfully deleted" });
        }
    }
}

Salon/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using SalonServices.Dto;

namespace Salon.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageService _imageServices;
		public ImageController(IImageService pImageServices)
		{
			this._imageServices = pImageServices;
		}

		public IActionResult SingleImage(int pImageId)
		{
            var lSingleImage = this._imageServices.GetById(pImageId);

            ImageViewModel lSingleImageViewModel = Mappings.Mapping.Mapper.Map<ImageViewModel>(lSingleImage);

			return View(lSingleImageViewModel);
		}

        public async Task<IActionResult> SuccessfulImages(int pPersonId)
        {
            List<ImageDto> lSuccessfulImages = await this._imageServices.GetSuccessfulImagesForPerson(pPersonId);

            List<ImageViewModel> lSuccessfulImagesViewModel = new List<ImageViewModel>();
            foreach (ImageDto lSuccesfulImage in lSuccessfulImages)
            {
                var lImageViewModel = Mappings.Mapping.Mapper.Map<ImageViewModel>(lSuccesfulImage);
                lSuccessfulImagesViewModel.Add(lImageViewModel);
            }

            return View(lSuccessfulImagesViewModel);
        }

		public async Task<IActionResult> AwardedImages(int pPersonId)
		{
			List<ImageSalonEntryDto> lSuccessfulImages = await this._imageServices.GetAwardedImagesForPerson(pPersonId);

			List<ImageSalonViewModel> lSuccessfulImagesViewModel = new List<ImageSalonViewModel>();
			int lAcceptanceNumber = 0;
			int lImageNumber = 0;
			string lImageName = "";
			foreach (ImageSalonEntryDto lSuccesfulImage in lSuccessfulImages)
			{
				var lImageSalonViewModel = Mappings.Mapping.Mapper.Map<ImageSalonViewModel>(lSuccesfulImage);
				if (lImageName != lImageSalonViewModel.ImageTitle)
				{
					lImageNumber++;
				}
				lAcceptanceNumber++;
				lImageName = lImageSalonViewModel.ImageTitle;
				lImageSalonViewModel.ImageNumber = lImageNumber;
				lImageSalonViewModel.AcceptanceNumber = lAcceptanceNumber;
				lSuccessfulImagesViewModel.Add(lImageSalonViewModel);
			}

			return View(lSuccessfulImagesViewModel);
		}

        public async Task<IActionResult> FiapImages(int pPersonId)
        {
            List<ImageSalonEntryDto> lFiapImages = await this._imageServices.GetSubmissionImages(pPersonId, "FIAP Levels", new DateTime(2021,2,25));
            List<ImageSalonViewModel> lFiapImagesViewModel = new List<ImageSalonViewModel>();
            int lAcceptanceNumber = 0;
            int lImageNumber = 0;
            string lImageName = "";
            foreach (ImageSalonEntryDto lFiapImage in lFiapImages)
            {
				var lImageSalonViewModel = Mappings.Mapping.Mapper.Map<ImageSalonViewModel>(lFiapImage);
                if (lImageName != lImageSalonViewModel.ImageTitle)
                {
                    lImageNumber++;
                }
				lAcceptanceNumber++;
                lImageName = lImageSalonViewModel.ImageTitle;
                lImageSalonViewModel.ImageNumber = lImageNumber;
                lImageSalonViewModel.AcceptanceNumber = lAcceptanceNumber;
				lFiapImagesViewModel.Add(lImageSalonViewModel);
            }

            return View(lFiapImagesViewModel);
        }
    }
}

Salon/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using Salon.Mappings;
using SalonServices.Dto;
using Salon.Models.Submission;

namespace Salon.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonAwardService _personAwardService;
        public PersonController(IPersonAwardService _personAwardService)
        {
            this._personAwardService = _personAwardService;
        }

        public async Task<IActionResult> Index()
        {
            var lDtos = await this._personAwardService.GetAllPersons();

            var lModel = new PersonIndexViewModel()
            {
                People = lDtos.Select(itm => Mapping.Mapper.Map<BasicPersonViewModel>(itm)).ToList(),
            };
            return View(lModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var lAwardLevelDto = await this._personAwardService.GetAwardLevelsForPerson(id);
            return View(Mapping.Mapper.Map<PersonAwardTableViewModel>(lAwardLevelDto));
        }

        [HttpGet]
        public async Task<IActionResult> PsaList(int pPersonId, string pSectionCode)
        {
            var lPsaSubmissionDto = await this._personAwardService.GetOrganisationSubmissionList(pPersonId, "PSA", pSectionCode);
            return View(Mapping.Mapper.Map<PsaSubmissionViewModel>(lPsaSubmissionDto));
        }
    }
}

Salon/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Salon.Models;
using SalonServices;
using Salon.Models.Submission;
using Salon.Mappings;
using SalonServices.Dto.Submission;
using SalonServices.Dto;

namespace Salon.Controllers
{
    public class SubmissionController : Controller
    {
        private readonly IReferenceServices _referenceServices;
        private readonly ISubmissionService _submissionService;
        private readonly ISalonYearService _salonYearService;


        public SubmissionController(IReferenceServices pReferenceServices, ISubmissionService pSubmissionService, ISalonYearService pSalonYearService)
        {
            this._referenceServices = pReferenceServices;
            this._submissionService = pSubmissionService;
            this._salonYearService = pSalonYearService;
        }

        #region Pages
        public async Task<IActionResult> Index(int pPersonId)
        {
            var lDtos = await this._submissionService.GetBasicSubmissionInfoByPersonId(pPersonId);
            var lItemVms = lDtos.Select(dto => Mapping.Mapper.Map<SubmissionListItemViewModel>(dto)).ToList();
            var lVm = new SubmissionListViewModel
            {
                PersonId = pPersonId,
                Items = lItemVms            
            };
            return View(lVm);
        }

        [HttpGet]
        public IActionResult AddSubmission(int pPersonId)
        {            
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SubmissionResults(int pSubmissionId)
        {
            var lResultsDto = await this._submissionService.GetSubmissionResults(pSubmissionId);
            var lVm = Mapping.Mapper.Map<SubmissionResultsViewModel>(lResultsDto);
            return View(lVm);
        }

        [HttpPost]
        public async Task<IActionResult> SubmissionResults([FromForm]SubmissionResultsViewModel pResultsVm)
        {
            if (!ModelState.IsValid)
            {
                return View(pResultsVm);
            }
            await this._submissionService.UpdateSubmissionResults(Mapping.Mapper.Map<SubmissionResultsDto>(pResultsVm));
            pResultsVm.ResultsUpdated = true;
            return View(pResultsVm);
        }
        #endregion

        #region Reference Data
        [HttpGet]
        public async Task<List<CircuitViewModel>> GetCircuits()
        {
            var lCircuitDtos = await this._referenceServices.GetCircuits();
            return lCircuitDtos.Select(dto => Mapping.Mapper.Map<CircuitViewModel>(dto)).ToList();
        }

        [HttpPost]
        public async Task<CreateCircuitViewModel> AddCircuit([FromBody]CreateCircuitViewModel pCircuitViewModel)
        {
            if (!ModelState.IsValid)
            {
                pCircuitViewModel.Errors = ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return pCircuitViewModel;
            }
            var lDto = Mapping.Mapper.Map<CreateCircuitDto>(pCircuitViewModel);
            var lReturnedDto = await this._referenceServices.CreateCircuit(lDto);
            return Mapping.Mapper.Map<CreateCircuitViewModel>(lReturnedDto);
        }

        [HttpGet]
        public async Task<List<SectionTypeViewModel>> GetSectionTypes()
        {
            var lSectionTypeDtos = await this._referenceServices.GetSectionTypes();
            return lSectionTypeDtos.Select(dto => Mapping.Mapper.Map<SectionTypeViewModel>(dto)).ToList();
        }
        
        [HttpGet]
        public async Task<List<OrganisationViewModel>> GetOrganisations()
        {
            var lOrganisationDtos = await this._referenceServices.GetOrganisations();
            return lOrganisationDtos.Select(dto => Mapping.Mapper.Map<OrganisationViewModel>(dto)).ToList();
        }

        [HttpGet]
        public async Task<List<CountryViewModel>> GetCountries()
        {
            var lCountryDtos = await this._referenceServices.GetCountries();
            return lCountryDtos.Select(dto => Mapping.Mapper.Map<CountryViewModel>(dto)).ToList();
        }
        #endregion

        #region Salon and Salon Year
        [HttpGet]
        public async Task<List<FullSalonInformationViewModel>> GetSalons()
        {
            var lDtos = await this._salonYearService.GetFullSalonInformation();
            return lDtos.Select(dto => Mapping.Mapper.Map<FullSalonInformationViewModel>(dto)).ToList();
        }

        [HttpPost]
        public async Task<CreateSalonViewModel> AddSalon([FromBody]CreateSalonViewModel pAddSalonVm)
        {
            if (!ModelState.IsValid)
            {
                pAddSalonVm.Errors = ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return pAddSalonVm;
            }
            var lDto = Mapping.Mapper.Map<CreateSalonDto>(pAddSalonVm);
            var lReturnedDto = await this._salonYearService.CreateSalon(lDto);
            return Mapping.Mapper.Map<CreateSalonViewModel>(lReturnedDto);
        }

        [HttpGet]
        public async Task<List<SalonYearInformationViewModel>> GetSalonYears(int pYear)
        {
            var lDtos = await this._salonYearService.GetSalonYears(pYear);
            return lDtos.Select(dto => Mapping.Mapper.Map<SalonYearInformationViewModel>(dto)).ToList();
        }

        [HttpPost]
        public async Task<CreateSalonYearViewModel> AddSalonYear([FromBody]CreateSalonYearViewModel pAddSalonYearVm)
        {
            if (!ModelState.IsValid)
            {
                pAddSalonYearVm.Errors = ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return pAddSalonYearVm;
            }
            var lDto = Mapping.Mapper.Map<CreateSalonYearDto>(pAddSalonYearVm);
            var lReturnedDto = await this._salonYearService.CreateSalonYear(lDto);
            return Mapping.Mapper.Map<CreateSalonYearViewModel>(lReturnedDto);
        }
        #endregion

        [HttpPost]
        public async Task<SubmissionSaveViewModel> AddSubmission([FromBody]SubmissionSaveViewModel pSaveViewModel)
        {
            if (!ModelState.IsValid)
            {
                pSaveViewModel.Errors = ModelState.Values.SelectMany(val => val.Errors).Select(err => err.ErrorMessage).ToList();
                return pSaveViewModel;
            }
            var lDto = Mapping.Mapper.Map<SubmissionSaveDto>(pSaveViewModel);
            var lReturnedSubmissionDto = await this._submissionService.CreateSubmission(lDto);
            return Mapping.Mapper.Map<SubmissionSaveViewModel>(lReturnedSubmissionDto);
        }
    }
}

Salon/Views/Person/Details.cshtml
@model Salon.Models.PersonAwardTableViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Person Award Achievement Progress for @Model.PersonName</h2>

<div>
    <div class="panel-group" id="achievement-accordion">
        @foreach (var item in Model.Organisations.Select((value, i) => new { i, value }))
        {
            var organisation = item.value;
            var orgNameWithoutSpace = organisation.OrginisationName.Replace(" ", "");
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#achievement-accordion" href="#@orgNameWithoutSpace-body">@organisation.OrginisationName</a>
                    </h4>
                </div>
                <div  id="@orgNameWithoutSpace-body" class="panel-collapse collapse @(item.i == 0 ? "in" : "")">
                    <div class="panel-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Award Name</th>
                                    <th>Achieved</th>
                                    <th>Acceptances Missing</th>
                                    <th>Awards Missing</th>
                                    <th>Countries Missing</th>
                                    <th>Distinct Images Missing</th>
                                    <th>Prints Missing</th>
                                    <th>Salons Missing</th>
                                    <th>Cost</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var award in organisation.Awards)
                                {
                                    <tr class="@(award.IsAwarded ? "success" : "danger")">
                                        <td>@award.AwardName</td>
                                        <td><span class="glyphicon @(award.IsAwarded ? "glyphicon-ok" : "glyphicon-remove")"></span></td>
                                        <td>@award.AcceptancesMissing <span style="font-size:0.7em">of @award.AcceptancesRequired</span></td>
                                        <td>@award.AwardsMissing <span style="font-size:0.7em">of @award.AwardsRequired</span></td>
                                        <td>@award.CountriesMissing <span style="font-size:0.7em">of @award.CountriesRequired</span></td>
                                        <td>@award.DistinctImagesMissing <span style="font-size:0.7em">of @award.DistinctImagesRequired</span></td>
                                        <td>@award.PrintsMissing <span style="font-size:0.7em">of @award.PrintsRequired</span></td>
                                        <td>@award.SalonsMissing <span style="font-size:0.7em">of @award.SalonsRequired</span></td>
                                        <td>£@Html.DisplayFor(modelItem => award.CostToAchieve)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Salon/Views/Person/Index.cshtml
@model Salon.Models.PersonIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>People</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    Name
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.People) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
				Acceptance Rate: @Html.DisplayFor(modelItem => item.AcceptanceRate)%
				<br>
                Total Submission Cost: £@Html.DisplayFor(modelItem => item.TotalCost),
				Cost Per Acceptance: £@Html.DisplayFor(modelItem => item.CostPerAcceptance)
				<br/>
                Unjudged Salons: @Html.DisplayFor(modelItem => item.UnjudgedSalonCount),
				Unjudged Images: @Html.DisplayFor(modelItem => item.UnjudgedImageCount)
				<br/>
				<a asp-action="Details" asp-route-id="@item.Id">Award Achievement</a> | 
                <a asp-action="Index" asp-controller="Submission" asp-route-pPersonId="@item.Id">Submissions</a> |
				<a asp-action="SuccessfulImages" asp-controller="Image" asp-route-pPersonId="@item.Id">Accepted Images</a> |
				<a asp-action="AwardedImages" asp-controller="Image" asp-route-pPersonId="@item.Id">Awarded Images</a> |
				<a asp-action="SuccessfulCountries" asp-controller="Country" asp-route-pPersonId="@item.Id">Countries</a> |
                <a asp-action="FiapImages" asp-controller="Image" asp-route-pPersonId="@item.Id">FIAP Submission</a>
            </td>
        </tr>
}
    </tbody>
</table>